# -*- coding: utf-8 -*-
"""pranay_model_v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x4--2AS-warbVa_IGpvthYWbpFMs1Zjh

## Importing Libraries
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import pickle

"""## Importing Data as Dataframe"""

column_names = ['id', 'diagnosis', 'radius_mean', 'texture_mean','perimeter_mean','area_mean','smoothness_mean','compactness_mean','concavity_mean','concave_points_mean','symmetry_mean','fractal_dimension_mean','radius_se','texture_se','perimeter_se','area_se','smoothness_se','compactness_se','concavity_se','concave_points_se','symmetry_se','fractal_dimension_se','radius_worst','texture_worst','perimeter_worst','area_worst','smoothness_worst','compactness_worst','concavity_worst','concave_points_worst','symmetry_worst','fractal_dimension_worst']
df = pd.read_csv('wdbc.data', names=column_names)

df.head()

"""## Seperating Data and Labels"""

X = df.drop('diagnosis', axis=1)
y = df['diagnosis']

"""## Split Data in training and testing sets"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

"""## Model Training using Decision Tree Classifier"""

dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

"""## Model Evaluation"""

y_pred = dtc.predict(X_test)

accuracy_score(y_test, y_pred)

"""## Saving the model"""

pickle.dump(dtc, open('pranay_model_v1.pkl', 'wb'))